# Generated by Django 4.0.1 on 2022-03-12 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gardenname', models.CharField(max_length=250)),
                ('gardendescription', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'gardens',
                'db_table': 'garden',
            },
        ),
        migrations.CreateModel(
            name='GardenType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=250)),
                ('typedescription', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'gardentypes',
                'db_table': 'gardentype',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantname', models.CharField(max_length=300)),
                ('plantdescr', models.TextField()),
                ('isseed', models.BooleanField(default=False)),
                ('dateplanted', models.DateField()),
                ('dateharvested', models.DateField()),
                ('gardenid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='garden.garden')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'plants',
                'db_table': 'plant',
            },
        ),
        migrations.AddField(
            model_name='garden',
            name='gardentype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='garden.gardentype'),
        ),
        migrations.AddField(
            model_name='garden',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
