# Generated by Django 4.0.1 on 2022-03-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='gardendescription',
            field=models.TextField(blank=True, null=True, verbose_name='Garden Description:'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='gardenname',
            field=models.CharField(max_length=250, verbose_name='Name your Garden:'),
        ),
        migrations.AlterField(
            model_name='gardentype',
            name='typedescription',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='gardentype',
            name='typename',
            field=models.CharField(max_length=250, verbose_name='Name of Type:'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='dateharvested',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='dateplanted',
            field=models.DateField(verbose_name='Date Planted:'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='isseed',
            field=models.BooleanField(default=False, verbose_name='Starting from seed?'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plantdescr',
            field=models.TextField(verbose_name='Plant Description:'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plantname',
            field=models.CharField(max_length=300, verbose_name='Plant Name:'),
        ),
    ]
